name: Format JavaScript with Prettier

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  format:
    name: Format JavaScript files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version of Node.js you prefer

      - name: Install dependencies
        run: npm install

      - name: Format code with Prettier
        run: npx prettier --write ".\react-frontend\src\pages\Home.js"  # Adjust the file glob as needed